name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with rsync over SSH
        env:
          SSH_KEY: ${{ secrets.LT_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          rsync -avz --delete -e "ssh -i key.pem -p 65002 -o StrictHostKeyChecking=no" ./ u962042185@77.37.57.103:/home/u962042185/domains/floressquad.com/public_html/wp-content/themes/college-picks/

      - name: Generate deployed files report
        run: |
          mkdir -p deployment-logs
          find . -type f | sort > deployment-logs/deployed-files.txt
          echo "Deployed files report generated at deployment-logs/deployed-files.txt"